### ISSUE TITLE
Use PEP8 to beautify your code

### ISSUE THREAD

**Issue by asarfraaz** [Thanmai1/Python_Exercises#2]
https://github.com/Thanmai1/Python_Exercises/blob/53b99da1d2292c7355defef3e64dfa69f3cb1205/fivetable.py#L8

It is highly recommended to write "readable" code ( that is easy on the eye ) in Python. There is a huge list of simple things that we can do to make this possible. Learn one thing at a time and put it to practice to imbibe the habits ( not just with Python, but with other programming languages as well )

Few recommendations for the code in this file can be found in this sub-section : https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements

**Comment by Thanmai1** [comment]
Inserted spaces in this expression i = i + 1
